joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0
  extra_joints:

    - name: 'roller_front_left_rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_right_rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_top_right_rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_down_right_rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_top_left_rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_down_left_rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_top_left_rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_down_left_rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_down_right_rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_top_right_rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0

    - name: 'roller_front_left_rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_right_rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_top_right_rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_down_right_rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_top_left_rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_down_left_rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_top_left_rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_down_left_rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0

    - name: 'roller_back_down_right_rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_top_right_rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0

    - name: 'roller_front_left_rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_right_rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_top_right_rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_down_right_rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_top_left_rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_down_left_rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_top_left_rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_down_left_rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_down_right_rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_top_right_rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0

    - name: 'roller_front_left_rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_right_rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_top_right_rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_down_right_rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_top_left_rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_down_left_rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_top_left_rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_front_down_left_rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_down_right_rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'roller_back_top_right_rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
